CREATE TABLE "ATOS"."TAREAS" (
		"CODIGO_TAREA" NUMBER(2 , 0) NOT NULL,
		"DESCRIPCION_TAREA" VARCHAR2(2000),
		"VINCULO" VARCHAR2(50)
	);

CREATE TABLE "ATOS"."USUARIOS" (
		"NOMBRE_USUARIO" VARCHAR2(20) NOT NULL,
		"PASSWORD" VARCHAR2(10),
		"CODIGO_ROL" NUMBER(2 , 0),
		"FECHA_ALTA" DATE,
		"FECHA_BAJA" DATE,
		"CARPETA_DOCUMENTACION" VARCHAR2(250),
		"IDIOMA" CHAR(2)
	);

CREATE TABLE "ATOS"."ROLES" (
		"CODIGO_ROL" NUMBER(2 , 0) NOT NULL,
		"DESCRIPCION_ROL" VARCHAR2(100)
	);

CREATE TABLE "ATOS"."ROLES_TAREAS" (
		"CODIGO_ROL" NUMBER(2 , 0) NOT NULL,
		"CODIGO_TAREA" NUMBER(2 , 0) NOT NULL
	);
	
	ALTER TABLE "ATOS"."ROLES" ADD CONSTRAINT "CODIGO_ROL_PK" PRIMARY KEY ("CODIGO_ROL");

ALTER TABLE "ATOS"."TAREAS" ADD CONSTRAINT "CODIGO_TAREA_PK" PRIMARY KEY ("CODIGO_TAREA");

ALTER TABLE "ATOS"."USUARIOS" ADD CONSTRAINT "NOMBRE_USUARIO_PK" PRIMARY KEY ("NOMBRE_USUARIO");

ALTER TABLE "ATOS"."ROLES_TAREAS" ADD CONSTRAINT "ROLES_TAREAS_PK" PRIMARY KEY ("CODIGO_ROL", "CODIGO_TAREA");

ALTER TABLE "ATOS"."ROLES_TAREAS" ADD CONSTRAINT "CODIGO_TAREA_FK" FOREIGN KEY ("CODIGO_TAREA")
	REFERENCES "ATOS"."TAREAS" ("CODIGO_TAREA")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "ATOS"."USUARIOS" ADD CONSTRAINT "CODIGO_ROL_USUARIOS_FK" FOREIGN KEY ("CODIGO_ROL")
	REFERENCES "ATOS"."ROLES" ("CODIGO_ROL")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "ATOS"."ROLES_TAREAS" ADD CONSTRAINT "CODIGO_ROL_FK" FOREIGN KEY ("CODIGO_ROL")
	REFERENCES "ATOS"."ROLES" ("CODIGO_ROL")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
	
	CREATE UNIQUE INDEX "ATOS"."CODIGO_TAREA_PK" ON "ATOS"."TAREAS" ("CODIGO_TAREA" ASC);

CREATE UNIQUE INDEX "ATOS"."NOMBRE_USUARIO_PK" ON "ATOS"."USUARIOS" ("NOMBRE_USUARIO" ASC);

CREATE UNIQUE INDEX "ATOS"."ROLES_TAREAS_PK" ON "ATOS"."ROLES_TAREAS" ("CODIGO_ROL" ASC, "CODIGO_TAREA" ASC);

CREATE UNIQUE INDEX "ATOS"."CODIGO_ROL_PK" ON "ATOS"."ROLES" ("CODIGO_ROL" ASC);